org.gradle.jvmargs=-Xmx2048M

mc_version=1.21.4
enabled_platforms=fabric,neoforge

archives_base_name=resourcefulconfigkt
maven_group=com.teamresourceful.resourcefulconfigkt

version=3.4.2

fabric_loader_version=0.16.9
fabric_api_version=0.110.5+1.21.4

neoforge_version=21.4.0-beta

## Mod Version
nightly=false